<a href="https://colab.research.google.com/github/ninja03jod/Machine_Learning_Projects/blob/main/Assumes_Global_EV_Prediction_On_Server.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pickle
import numpy as np
import pandas as pd

In [6]:
encode = pickle.load(open("LabelEncoder.pkl","rb"))
pipe = pickle.load(open("Global_EV_Value_By_RandomForest.pkl","rb"))
Dec_pipe = pickle.load(open("Global_EV_Value_By_DecTree.pkl","rb"))

In [7]:
test = [[22,0,2,3,1,2018,5]]
test

[[22, 0, 2, 3, 1, 2018, 5]]

In [8]:
# lets test the record by random forest:
pipe.predict(test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([0.4661002])

In [9]:
# the actual output is --> 0.17
# predicted output is --> 0.46

print(0.17 - 0.46)

-0.29000000000000004


In [11]:
# lets test the record with decision Tree regressor:
Dec_pipe.predict(test)

array([8.])

In [12]:
# actual outout --> 0.17
# predicted output --> 8.
print(8 - 0.17)

7.83


In [13]:
# lets chcek the anothe record:
pipe.predict([[14,0,2,1,1,2017,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([1.50672998])

In [14]:
# actual is --> 14.00
# error
14 - 1.50

12.5

In [15]:
Dec_pipe.predict([[14,0,2,1,1,2017,5]])

array([8.])

In [16]:
# actual is --> 14.00
14 - 8
# erorr

6